import type { RuleModule } from './types';
import {
  handlePlaceInitialSettlement,
  handlePlaceInitialRoad,
  handleRollDice,
  handleDiscard,
  handleMoveRobber,
  handleBuildSettlement,
  handleBuildCity,
  handleBuildRoad,
  handleBuyDevCard,
  handlePlayKnight,
  handlePlayRoadBuilding,
  handlePlayYearOfPlenty,
  handlePlayMonopoly,
  handleBankTrade,
  handleEndTurn,
} from '../actions';

export const baseModule: RuleModule = {
  id: 'base',
  name: 'Base Game',
  handlers: {
    placeInitialSettlement: handlePlaceInitialSettlement as never,
    placeInitialRoad: handlePlaceInitialRoad as never,
    rollDice: handleRollDice as never,
    discard: handleDiscard as never,
    moveRobber: handleMoveRobber as never,
    buildSettlement: handleBuildSettlement as never,
    buildCity: handleBuildCity as never,
    buildRoad: handleBuildRoad as never,
    buyDevCard: handleBuyDevCard as never,
    playKnight: handlePlayKnight as never,
    playRoadBuilding: handlePlayRoadBuilding as never,
    playYearOfPlenty: handlePlayYearOfPlenty as never,
    playMonopoly: handlePlayMonopoly as never,
    bankTrade: handleBankTrade as never,
    endTurn: handleEndTurn as never,
  },
};
